### ISSUE TITLE
Change case of property 'String'

### ISSUE THREAD

**Issue by andjsrk** [Lukince/Hangul4deno#1]
https://github.com/Lukince/Hangul4deno/blob/a12e263b4b5d5acde98b019fe8ef17550b1d7c1c/src/entities/hangul.ts#L22

Property `String` is not a class, but it's using pascal case.

**Comment by qluana7** [comment]
because i used C# before, It seems that the habit of that time remains. How about change name to _string? or content? can you suggest something good name for that property?

**Comment by qluana7** [comment]
Ok. That's not important property. I will change name to content next build version.
